server:
  port: 7002
 
spring:
  datasource:
    url: jdbc:h2:../test
    username: test
    password: 
    driver-class-name: org.h2.Driver
  application:
    name: product
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/